name: Bump Package Version

on:
  workflow_dispatch:
    inputs:
      package-name:
        description: "Name of the NPM package to bump"
        required: true
        type: string
      version:
        description: "Version to bump to (defaults to latest)"
        default: "latest"
        required: false
        type: string
      branch:
        description: "Base branch name (defaults to main)"
        default: "main"
        required: false
        type: string

jobs:
  bump_version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js and NPM
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      - name: Replace special characters in package name
        uses: bluwy/substitute-string-action@v1
        id: replaceinname
        with:
          _input-text: ${{ github.event.inputs.package-name}}
          "@": ""
          "/": "-"
          ".": "-"

      - name: Replace special characters in version
        uses: bluwy/substitute-string-action@v1
        id: replaceinversion
        with:
          _input-text: ${{ github.event.inputs.version }}
          .: "-"

      - name: Create a new branch
        run: |
          BRANCH_NAME=chore/bump-${{ steps.replaceinname.outputs.result }}-to-${{steps.replaceinversion.outputs.result}}
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          git config --global --add safe.directory /github/workspace
          git checkout -b $BRANCH_NAME
          git fetch origin
          git reset --hard origin/${{ github.event.inputs.branch }}

      - name: Install Dependencies
        run: npm ci

      - name: Bump Package Version
        run: |
          VERSION=${{ github.event.inputs.version }}
          PACKAGE_NAME=${{ github.event.inputs.package-name }}
          npm install "$PACKAGE_NAME@$VERSION"
          echo "Bumped $PACKAGE_NAME to version $VERSION"

      - name: Commit & Push Version Bump
        run: |
          PACKAGE_NAME=${{ github.event.inputs.package-name }}
          VERSION=${{ github.event.inputs.version }}
          COMMIT_MESSAGE="chore: bump $PACKAGE_NAME to $VERSION"
          BRANCH_NAME=chore/bump-${{ steps.replaceinname.outputs.result }}-to-${{steps.replaceinversion.outputs.result}}
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "$COMMIT_MESSAGE" --no-verify --all
          git push origin $BRANCH_NAME

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          title: Chore/bump ${{ github.event.inputs.package-name }}
          commit-message: $COMMIT_MESSAGE
          branch: ${{ github.head_ref }}
          base: ${{ github.event.inputs.branch }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: repo-sync/pull-request@v2
        name: pull-request
        env:
          PACKAGE_NAME: ${{ github.event.inputs.package-name }}
          VERSION: ${{ github.event.inputs.version }}
          BRANCH_NAME: chore/bump-${{ steps.replaceinname.outputs.result }}-to-${{steps.replaceinversion.outputs.result}}
        with:
          source_branch: $BRANCH_NAME
          destination_branch: ${{ github.event.inputs.branch }}
          pr_title: Chore/bump ${{ github.event.inputs.package-name }}
          pr_body: |
            <i>
            Automatically bump $PACKAGE_NAME to $VERSION <br>
            Automation was ran by @${{ github.actor }}
            </i>
          github_token: ${{ secrets.GITHUB_TOKEN }}
